
import { Property } from '@activepieces/pieces-framework';
export const wedofCommon = {
  baseUrl: 'https://staging.wedof.fr/api',
  host: 'https://staging.wedof.fr/api',
  scope: Property.StaticMultiSelectDropdown({
    displayName: 'Etat du dossier de formations',
    required: true,
    options: {
      options: [
        { value: 'registrationFolder.created', label: 'Créer' },
        { value: 'registrationFolder.updated', label: 'Mis à jour' },
        { value: 'registrationFolder.notProcessed', label: 'Non traité' },
        { value: 'registrationFolder.validated', label: 'Validé' },
        { value: 'registrationFolder.waitingAcceptation', label: 'Validé (En cours d\'instruction Pole emploi)' },
        { value: 'registrationFolder.accepted', label: 'Accepté' },
        { value: 'registrationFolder.inTraining', label: 'En formation' },
        { value: 'registrationFolder.terminated', label: 'Sortie de formation' },
        { value: 'registrationFolder.serviceDoneDeclared', label: 'Service fait déclaré' },
        { value: 'registrationFolder.serviceDoneValidated', label: 'Service fait validé' },
        { value: 'registrationFolderFile.added', label: 'Document ajouté' },
        { value: 'registrationFolderFile.updated', label: 'Document mis a jour' },
        { value: 'registrationFolderFile.deleted', label: 'Document supprimé' },
        { value: 'registrationFolderFile.valid', label: 'Document validé' },
        { value: 'registrationFolderFile.refused', label: 'Document refusé' },
        { value: 'registrationFolderFile.toReview', label: 'Document à vérifier' },
        { value: 'registrationFolder.canceledByAttendee', label: 'Annulé (par le titulaire)' },
        { value: 'registrationFolder.canceledByAttendeeNotRealized', label: 'Annulation titulaire (non réalisé)' },
        { value: 'registrationFolder.canceledByOrganism', label: 'Annulé (par l\'organisme)' },
        { value: 'registrationFolder.canceledByFinancer', label: 'Annulé (par le financeur)' },
        { value: 'registrationFolder.rejectedWithoutTitulaireSuite', label: 'Annulé sans suite' },
        { value: 'registrationFolder.refusedByAttendee', label: 'Refus titulaire' },
        { value: 'registrationFolder.refusedByOrganism', label: 'Refusé (par l\'organisme)' },
        { value: 'registrationFolder.refusedByFinancer', label: 'Refusé (par le financeur)' },
        { value: 'registrationFolder.refusedByFinancer', label: 'Refusé (par le financeur)' },
        { value: 'registrationFolderBilling.notBillable', label: 'Pas facturable' },
        { value: 'registrationFolderBilling.depositWait', label: 'Acompte en attente de dépot' },
        { value: 'registrationFolderBilling.depositPaid', label: 'Acompte déposé' },
        { value: 'registrationFolderBilling.toBill', label: 'A facturer' },
        { value: 'registrationFolderBilling.billed', label: 'Facturé' },
        { value: 'registrationFolderBilling.paid', label: 'Payé' },
      ],
      disabled: false,
    },
  }),

};
